/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author alexandralecuna
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        starTrekLogo = new javax.swing.JLabel();
        starWarsLogo = new javax.swing.JLabel();
        starSimulation = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        starTreckNumWin = new javax.swing.JLabel();
        starTreckCharacter = new javax.swing.JPanel();
        starWarsCharacter = new javax.swing.JPanel();
        starWarsID = new javax.swing.JLabel();
        starWarsNumWin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        starTreckID = new javax.swing.JLabel();
        starWarsName = new javax.swing.JLabel();
        starTreckName1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        velocidad = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        starTreckNivel3 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        starTreckNivel1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        starTreckNivel2 = new javax.swing.JList<>();
        vsLabel2 = new javax.swing.JLabel();
        jLabelN1 = new javax.swing.JLabel();
        jLabeln2 = new javax.swing.JLabel();
        jLabelN3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        starWarsNivel3 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        starWarsNivel1 = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        starWarsNivel2 = new javax.swing.JList<>();
        jLabelN2 = new javax.swing.JLabel();
        jLabeln3 = new javax.swing.JLabel();
        jLabelN4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        starTrekLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StarTrekIMGs/Logo.png"))); // NOI18N
        jPanel1.add(starTrekLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 410, 130));

        starWarsLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StarWarsIMGs/vecteezy_star-wars-logo-png-star-wars-icon-transparent-png_27127457 (1).png"))); // NOI18N
        jPanel1.add(starWarsLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, -10, 490, 200));

        starSimulation.setBackground(new java.awt.Color(255, 255, 0));
        starSimulation.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        starSimulation.setText("Start");
        starSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starSimulationActionPerformed(evt);
            }
        });
        jPanel1.add(starSimulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 150, 50));

        result.setFont(new java.awt.Font("Phosphate", 1, 48)); // NOI18N
        result.setForeground(new java.awt.Color(255, 255, 0));
        result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        result.setText("Resultado");
        jPanel1.add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, -1, -1));

        jLabel1.setFont(new java.awt.Font("Silom", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ganadores:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, -1, -1));

        starTreckNumWin.setFont(new java.awt.Font("Silom", 1, 24)); // NOI18N
        starTreckNumWin.setForeground(new java.awt.Color(255, 255, 255));
        starTreckNumWin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        starTreckNumWin.setText("0");
        jPanel1.add(starTreckNumWin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        javax.swing.GroupLayout starTreckCharacterLayout = new javax.swing.GroupLayout(starTreckCharacter);
        starTreckCharacter.setLayout(starTreckCharacterLayout);
        starTreckCharacterLayout.setHorizontalGroup(
            starTreckCharacterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        starTreckCharacterLayout.setVerticalGroup(
            starTreckCharacterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel1.add(starTreckCharacter, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 160, 200));

        javax.swing.GroupLayout starWarsCharacterLayout = new javax.swing.GroupLayout(starWarsCharacter);
        starWarsCharacter.setLayout(starWarsCharacterLayout);
        starWarsCharacterLayout.setHorizontalGroup(
            starWarsCharacterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        starWarsCharacterLayout.setVerticalGroup(
            starWarsCharacterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel1.add(starWarsCharacter, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        starWarsID.setFont(new java.awt.Font("Silom", 1, 24)); // NOI18N
        starWarsID.setForeground(new java.awt.Color(255, 255, 255));
        starWarsID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        starWarsID.setText("ID");
        jPanel1.add(starWarsID, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, -1, -1));

        starWarsNumWin.setFont(new java.awt.Font("Silom", 1, 24)); // NOI18N
        starWarsNumWin.setForeground(new java.awt.Color(255, 255, 255));
        starWarsNumWin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        starWarsNumWin.setText("0");
        jPanel1.add(starWarsNumWin, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Silom", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ganadores:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        starTreckID.setFont(new java.awt.Font("Silom", 1, 24)); // NOI18N
        starTreckID.setForeground(new java.awt.Color(255, 255, 255));
        starTreckID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        starTreckID.setText("ID");
        jPanel1.add(starTreckID, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        starWarsName.setFont(new java.awt.Font("Silom", 1, 24)); // NOI18N
        starWarsName.setForeground(new java.awt.Color(255, 255, 255));
        starWarsName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        starWarsName.setText("Nombre");
        jPanel1.add(starWarsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, -1, -1));

        starTreckName1.setFont(new java.awt.Font("Silom", 1, 24)); // NOI18N
        starTreckName1.setForeground(new java.awt.Color(255, 255, 255));
        starTreckName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        starTreckName1.setText("Nombre");
        jPanel1.add(starTreckName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Velocidad:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        velocidad.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        velocidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.5", "1", "1.5", "2" }));
        jPanel1.add(velocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, -1));

        starTreckNivel3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(starTreckNivel3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 120, 80));

        starTreckNivel1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(starTreckNivel1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 120, 80));

        starTreckNivel2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(starTreckNivel2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 120, 80));

        vsLabel2.setFont(new java.awt.Font("Phosphate", 1, 48)); // NOI18N
        vsLabel2.setForeground(new java.awt.Color(255, 255, 0));
        vsLabel2.setText("VS");
        jPanel1.add(vsLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));

        jLabelN1.setFont(new java.awt.Font("Phosphate", 1, 36)); // NOI18N
        jLabelN1.setForeground(new java.awt.Color(255, 255, 0));
        jLabelN1.setText("Nivel 1");
        jPanel1.add(jLabelN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabeln2.setFont(new java.awt.Font("Phosphate", 1, 36)); // NOI18N
        jLabeln2.setForeground(new java.awt.Color(255, 255, 0));
        jLabeln2.setText("Nivel 2");
        jPanel1.add(jLabeln2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabelN3.setFont(new java.awt.Font("Phosphate", 1, 36)); // NOI18N
        jLabelN3.setForeground(new java.awt.Color(255, 255, 0));
        jLabelN3.setText("Nivel 3");
        jPanel1.add(jLabelN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        starWarsNivel3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(starWarsNivel3);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 480, 120, 80));

        starWarsNivel1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(starWarsNivel1);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 120, 80));

        starWarsNivel2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(starWarsNivel2);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 380, 120, 80));

        jLabelN2.setFont(new java.awt.Font("Phosphate", 1, 36)); // NOI18N
        jLabelN2.setForeground(new java.awt.Color(255, 255, 0));
        jLabelN2.setText("Nivel 1");
        jPanel1.add(jLabelN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, -1, -1));

        jLabeln3.setFont(new java.awt.Font("Phosphate", 1, 36)); // NOI18N
        jLabeln3.setForeground(new java.awt.Color(255, 255, 0));
        jLabeln3.setText("Nivel 2");
        jPanel1.add(jLabeln3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, -1, -1));

        jLabelN4.setFont(new java.awt.Font("Phosphate", 1, 36)); // NOI18N
        jLabelN4.setForeground(new java.awt.Color(255, 255, 0));
        jLabelN4.setText("Nivel 3");
        jPanel1.add(jLabelN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void starSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starSimulationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_starSimulationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelN1;
    private javax.swing.JLabel jLabelN2;
    private javax.swing.JLabel jLabelN3;
    private javax.swing.JLabel jLabelN4;
    private javax.swing.JLabel jLabeln2;
    private javax.swing.JLabel jLabeln3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel result;
    private javax.swing.JButton starSimulation;
    private javax.swing.JPanel starTreckCharacter;
    private javax.swing.JLabel starTreckID;
    private javax.swing.JLabel starTreckName1;
    private javax.swing.JList<String> starTreckNivel1;
    private javax.swing.JList<String> starTreckNivel2;
    private javax.swing.JList<String> starTreckNivel3;
    private javax.swing.JLabel starTreckNumWin;
    private javax.swing.JLabel starTrekLogo;
    private javax.swing.JPanel starWarsCharacter;
    private javax.swing.JLabel starWarsID;
    private javax.swing.JLabel starWarsLogo;
    private javax.swing.JLabel starWarsName;
    private javax.swing.JList<String> starWarsNivel1;
    private javax.swing.JList<String> starWarsNivel2;
    private javax.swing.JList<String> starWarsNivel3;
    private javax.swing.JLabel starWarsNumWin;
    private javax.swing.JComboBox<String> velocidad;
    private javax.swing.JLabel vsLabel2;
    // End of variables declaration//GEN-END:variables
}
